### ISSUE TITLE
Video problem

### ISSUE THREAD

**Issue by seyma-tas** [learn-co-curriculum/dsc-normal-distribution#3]
"Here is an interesting youtube video highlighting this phenomenon for now. We will consider this in detail later."
The video is currently unavailable. So it is necessary to remove the link or change the link with a working video.

**Comment by melfriedman** [comment]
I'm having this issue too, doesn't seem to be resolved :( 
![image](https://user-images.githubusercontent.com/68208636/98436121-9bb8f700-208d-11eb-802c-2d845e6fbe17.png)

**Comment by hoffm386** [comment]
Link removed by [this commit](https://github.com/learn-co-curriculum/dsc-normal-distribution/commit/ef129fe722a784538418df2ff1212b8884ea7056). Thanks for flagging!
